#if !canImport(ObjectiveC)
import XCTest

extension EventTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EventTests = [
        ("testBadEventRoute", testBadEventRoute),
        ("testMockEvents", testMockEvents),
        ("testRandomEvent", testRandomEvent),
        ("testSortedEvents", testSortedEvents),
    ]
}

extension LocationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LocationTests = [
        ("testBadLocationRoute", testBadLocationRoute),
        ("testMockLocations", testMockLocations),
        ("testRandomLocation", testRandomLocation),
        ("testSortedLocations", testSortedLocations),
    ]
}

extension UserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UserTests = [
        ("testBadUserRoute", testBadUserRoute),
        ("testMockUsers", testMockUsers),
        ("testRandomUser", testRandomUser),
        ("testSortedUsers", testSortedUsers),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EventTests.__allTests__EventTests),
        testCase(LocationTests.__allTests__LocationTests),
        testCase(UserTests.__allTests__UserTests),
    ]
}
#endif
