name: Deploy to Prod
on:
  push:
    tags:
    - '*'
jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@master
        
      - name: Display the release tag
        run: |
          echo $GITHUB_REF
          fullRef=$GITHUB_REF
          IFS='/' read -a refs <<< "${fullRef}"
          echo ${refs[2]}
          echo "::set-env name=release_tag::${refs[2]}"

      - name: Update tag name
        run: echo $release_tag > $GITHUB_WORKSPACE/_meta

      - name: Update deployment file
        run: ./update-prod-version.sh $release_tag

      - name: install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
      - name: Build container image with release tag
        uses: docker/build-push-action@v1
        with:
          username: dokun1
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dokun1/afterparty-server
          tags: "${release_tag}"
          build_args: env=docker

      - name: Build container image with latest tag
        uses: docker/build-push-action@v1
        with:
          username: dokun1
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dokun1/afterparty-server
          tags: latest
          build_args: env=docker

      - name: Save DO kubeconfig
        run: doctl kubernetes cluster kubeconfig save afterparty-cluster
     
      - name: Deploy to DO Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/kube/afterparty-deployment.yaml
     
      - name: Verify deployment
        run: kubectl rollout status deployment/afterparty