name: Run Tests On Pull Request
on:
  pull_request:
jobs:
  linux_tests:
    name: Run Linux Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@master

      - name: Run tests
        run: ./swift-test-linux.sh

  mac_tests:
    name: Run Mac Tests
    runs-on: macos-10.15
    steps:
      - name: Checkout Actions
        uses: actions/checkout@master

      - name: Run tests
        run: swift test