name: Pull Request Testing
on:
  pull_request:
jobs:
  mac_build:
    name: Build on Mac
    runs-on: macos-10.15
    steps:
      - name: Checkout Actions
        uses: actions/checkout@master

      - name: Install libressl
        run: brew install libressl

      - name: Run tests
        run: |
          swift package resolve
          swift package clean
          swift build

  linux_tests:
    needs: mac_build
    name: Run Linux Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@master

      - name: Run tests
        run: ./swift-test-linux.sh

  mac_tests:
    needs: mac_build
    name: Run Mac Tests
    runs-on: macos-10.15
    steps:
      - name: Checkout Actions
        uses: actions/checkout@master

      - name: Install libressl
        run: brew install libressl

      - name: Run tests
        run: |
          swift package resolve
          swift package clean
          swift test